apiVersion: v1
kind: Service
metadata:
  name: {{ include "discsync-embeddings.name" . }}
  labels:
    {{- include "discsync-embeddings.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "discsync-embeddings.name" . }}
    {{- include "discsync-embeddings.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort | default 8080 }}